name: generator

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        
      - name: Check if out exists
        uses: ./.github/actions
      
      - name: Show if out exists
        run: ls -a 

      - name: Run Docker From Worflow
        run: docker run --rm --name devtest -v "./.github/actions://local" openapitools/openapi-generator-cli generate -i //local/mySwagger.json -g csharp-netcore -o //local/out  
      
      - name: Set Up .Net Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      
      - name: Show generated csharp project in ./out/src/Org.OpenAPITools
        run: ls ./out/src/Org.OpenAPITools
        
      - name: Install dependencies
        run: sudo dotnet restore ./out/src/Org.OpenAPITools/Org.OpenAPITools.csproj

      - name: Publish Nugget
        run: | 
          cd ./out
          sudo dotnet pack --configuration Release -o ./out/releases
        
      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v1.0.0
        with: 
           name: csharp
           path: ./out

